# Generated by Django 3.0.1 on 2020-05-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPage', '0002_auto_20200328_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'permissions': (('can_swap_strats', 'Can swap the strategies between two players'), ('can_see_hidden_strats', 'Can see hidden strategies'))},
        ),
    ]
