# Generated by Django 3.0.1 on 2020-01-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0003_auto_20200109_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='nade',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nade',
            name='nade_type',
            field=models.CharField(choices=[('F', 'Flash'), ('S', 'Smoke'), ('M', 'Molotov'), ('H', 'HE Grenade')], max_length=1),
        ),
    ]
