# Generated by Django 3.0.1 on 2020-01-17 21:58

import StratBook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0010_auto_20200117_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=StratBook.models.map_directory_path),
        ),
    ]
