# Generated by Django 3.0.1 on 2020-03-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_admin_page', 'Can view admin page'), ('can_change_player_groups', 'Can change the groups of a player')),
            },
        ),
    ]
