# Generated by Django 3.0.1 on 2019-12-27 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='active_duty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='team',
            field=models.CharField(default='exit', max_length=2),
            preserve_default=False,
        ),
    ]
