# Generated by Django 3.0.1 on 2020-01-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0004_auto_20200111_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nade',
            old_name='detail',
            new_name='descrition',
        ),
    ]
