# Generated by Django 3.0.1 on 2020-01-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0005_auto_20200111_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nade',
            old_name='descrition',
            new_name='description',
        ),
    ]
