# Generated by Django 3.0.1 on 2020-01-12 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StratBook', '0006_auto_20200111_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='description',
        ),
        migrations.AlterField(
            model_name='nade',
            name='nade_type',
            field=models.CharField(choices=[('S', 'Smoke'), ('M', 'Molotov'), ('F', 'Flash'), ('H', 'HE Grenade')], max_length=1),
        ),
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('nade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StratBook.Nade')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
