# Generated by Django 3.0.1 on 2020-01-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0007_auto_20200112_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bullet',
            old_name='description',
            new_name='text',
        ),
        migrations.AddField(
            model_name='bullet',
            name='strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StratBook.Strategy'),
            preserve_default=False,
        ),
    ]
