# Generated by Django 3.0.1 on 2020-01-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0008_auto_20200113_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
