# Generated by Django 3.0.1 on 2020-02-20 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StratBook', '0012_playerordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerordering',
            name='player',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
