# Generated by Django 3.0.1 on 2020-03-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0013_auto_20200220_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerordering',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
