# Generated by Django 3.0.1 on 2020-04-04 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0015_auto_20200331_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date added'),
        ),
    ]
