# Generated by Django 3.0.1 on 2020-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StratBook', '0016_strategy_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
